@startuml


!define BCW lightgreen

actor user

interface "Gamepad" as gp

package JetRacer {

  component karen <<nodejs/Manager>> 
  
  component drivetrain <<actor>>
  component presencemanager <<sensor>> as pm 
  component  gamepad <<sensor/velocitas>> #BCW
  
  ' interface can
  component kuksa <<kuksa/VSS>> #BCW
  
  interface i2c
  interface bluetooth
  

  node "motor/steering"  as ms 


  pm <-up-> kuksa
  
  ' kuksa <.down.> can

  karen <-down-> kuksa
  
  kuksa <-down-> gamepad
  gamepad <-down-> gp
  gp <..> user
  


  pm <-down-> bluetooth
  bluetooth <..> user



  drivetrain <-up-> kuksa
  drivetrain <-down-> i2c
  i2c <-> ms
  
}



package screen {
  component hmi <<NodeJS/HTML>>
}



' package  Raspberry{ 


' }

kuksa <-> hmi



@enduml